name: Deno for Azure
description: Publish a Deno app to Azure App Service on Linux
branding:
  icon: arrow-up-circle
  color: blue
inputs:
  app-name:
    description: Name of the Azure Web App
    required: true
  resource-group:
    description: Name of the resource group
    required: true
  package:
    description: Path to zip package to deploy
    required: true
  script-file:
    description: Path to script to pass to Deno run
    required: true
  deno-version:
    description: Version of Deno to use
    required: true
runs:
  using: node12
  main: dist/index.js
