name: Build and push Docker image

on:
  workflow_dispatch:
    inputs:
      denoVersion:
        description: 'Deno Version'
        required: true
        default: '1.16.2'
      pushLatest:
        description: 'Also push latest'
        required: true
        default: 'false'

jobs:
  buildAndPush:
    name: Build and push Deno ${{ github.event.inputs.denoVersion }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: progging
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: progging/deno-for-azure
          build_args: DENO_VERSION=${{ github.event.inputs.denoVersion }}
          tags: ${{ github.event.inputs.denoVersion }}
          path: container

      - name: Push latest tag
        if: github.event.inputs.pushLatest == 'true'
        uses: docker/build-push-action@v1
        with:
          username: progging
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: progging/deno-for-azure
          build_args: DENO_VERSION=${{ github.event.inputs.denoVersion }}
          tags: latest
          path: container
